In [1]:
import numpy as np

In [2]:
from util import numerical_gradient

In [3]:
def function_2(x):
    return x[0] ** 2 + x[1] ** 2

In [5]:
numerical_gradient(function_2, np.array([3, 4]))

array([25000, 35000])

In [6]:
numerical_gradient(function_2, np.array([0.0, 2.0]))

array([0., 4.])

In [7]:
numerical_gradient(function_2, np.array([3., 4.]))

array([6., 8.])